// <auto-generated />
using ApiProj.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ApiProj.Migrations
{
    [DbContext(typeof(ClienteContext))]
    [Migration("20210706001014_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.7");

            modelBuilder.Entity("ApiProj.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CDFLIFOR")
                        .HasComment("Código Cliente");

                    b.Property<string>("CNPJouCpf")
                        .HasColumnType("varchar(18)")
                        .HasColumnName("CNPJ_CPF")
                        .HasComment("CNPJ / CPF");

                    b.Property<short>("DDD")
                        .HasColumnType("smallint(6)")
                        .HasColumnName("DDD_FONE")
                        .HasComment("DDD Fone");

                    b.Property<string>("Fone")
                        .HasColumnType("varchar(15)")
                        .HasColumnName("FONE")
                        .HasComment("Fone");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(60)")
                        .HasColumnName("NOCLIFOR")
                        .HasComment("Nome cliente/Fornecedor");

                    b.HasKey("Id");

                    b.ToTable("Clientes");
                });
#pragma warning restore 612, 618
        }
    }
}
